name: time-exchange

services:
  app:
    build: .
    container_name: time-exchange-app
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=time-exchange-db
      - REDIS_URL=redis://time-exchange-redis:6379/0
      - ALLOWED_HOSTS=["stating.arisu.one", "time.arisu.one"]
    depends_on:
      - db
      - redis
    networks:
      - stating-zone
      - app-internal

  redis:
    image: redis:alpine
    container_name: time-exchange-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-internal

  db:
    image: postgres:15-alpine
    container_name: time-exchange-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-internal

volumes:
  redis_data:
  postgres_data:

networks:
  stating-zone:
    external: true
  app-internal:
    driver: bridge